#!/bin/bash
######################################################################
# Bildschirme/Beamer steuern und verwalten
# 2016-12-13; Florian Jansen; to the right, above
#
######################################################################
# xrandr --output eDP1 --auto --pos 0x1080 --output VGA1 --auto --pos 0x0 --output HDMI1 --auto --pos 1920x0
######################################################################
# Variabeln
INTERN="eDP-1"
EXTERN=$(xrandr | grep -w connected  | awk  '{print $1}' | sed -sn 2p)

echo $EXTERN
######################################################################
# Funktionen

PrintUsage(){
cat << EOI
Usage:
 bildschirm < modes | intern | extern | clone | above | right | hochkant >

Optionen:
  modes     Moegliche Modes ausgeben
  intern    Nur internen Bildschirm verwenden
  extern    Nur externer Bildschirm verwenden
  clone     Gleiche Ausgabe auf beiden Bildschirmen
  above     Bild auf externem Bildschirm nach oben erweitern
  right     Bild auf externem Bildschirm nach rechts erweitern
  hochkannt Bild auf externem Bildschirm hochkant stellen

EOI
}

######################################################################
# Main
case $1 in
  modes)
    xrandr -q
    ;;
  off)
    xrandr --auto
    ;;
  intern)
    xrandr --output $INTERN --auto --output $EXTERN --off
    ;;
  extern)
    xrandr --output $INTERN --off --output $EXTERN --auto
    ;;
  clone)
    CLONERES=`xrandr --query | awk '/^ *[0-9]*x[0-9]*/{ print $1 }' | sort -n | uniq -d | tail -1`
    xrandr --output $INTERN --mode $CLONERES --output $EXTERN --same-as $INTERN --mode $CLONERES
    ;;
  1024)
     xrandr --output $INTERN --mode 1024x768 --output $EXTERN --same-as $INTERN --mode 1024x768
    ;;
  1280)
     xrandr --output $INTERN --mode 1280x1024 --output $EXTERN --same-as $INTERN --mode 1280x1024
    ;;
  above)
    xrandr --output $INTERN --auto --output $EXTERN --auto --above $INTERN
    # xrandr --output $EXTERN --mode $EXTRES --pos 1280x0 --output $INTERN --mode $INTRES --pos 0x400
    ;;
  right)
    xrandr --output $INTERN --auto --output $EXTERN --auto --right-of $INTERN
    ;;
  hochkant)
    xrandr --output $INTERN --auto --pos 1440x1486 --output $EXTERN --auto --pos 0x0 --rotate left
    ;;
  *)
    PrintUsage
    ;;
esac

# EOF
