#!/bin/bash
export DISPLAY=:0.0 
cd ~
if grep '/net autofs' /etc/mtab > /dev/null 2>&1 ; then 
	notify-send "Starting backup ..."
	obnam --config=.obnam.conf force-lock
	obnam --config=.obnam.conf forget --keep=72h,14d,10w,36m,10y
	obnam --config=.obnam.conf --client=florian-X1-Carbon backup
# Cronjob mit Verschlüsseln nicht möglich
	if [ "$?" -ne 0 ]; then
	  notify-send -t 10000 "Unable to finish obnam backup."
	  exit 1
	else
	  notify-send "Finished backup."
	fi
else 
  notify-send -t 1000 "Backup drive not available ..."
fi
### Mount backup
# mkdir ~/obnam
# obnam --config=~/.obnam.conf generations
## obnam mount --repository /net/NAS/mnt/HD/HD_a2/backup --client-name jansen-UX31A --to=/home/jansen/obnam
# obnam mount --to=~/./obnam --log=~/mount.log
# fusermount -u ~/obnam
# obnam forget --keep=72h,14d,10w,24m

